/* Author: @moser-jose */
/* Date: 2025-09-05 */
/*
  - Builds src/types/Icon.d.ts mapping: { [variant]: [nameKey1, nameKey2, ...] }
  - Name key is the file path relative to the variant dir without extension (e.g. "bell-bing")
*/

export interface IconNamesByVariant {
  'bold': 'archive' | 'archive-check' | 'archive-down' | 'archive-down-minimlistic' | 'archive-minimalistic' | 'archive-up' | 'archive-up-minimlistic' | 'arrow-to-down-left' | 'arrow-to-down-right' | 'arrow-to-top-left' | 'arrow-to-top-right' | 'bell' | 'bell-bing' | 'bell-off' | 'circle-bottom-down' | 'circle-bottom-up' | 'circle-top-down' | 'circle-top-up' | 'clipboard' | 'clipboard-add' | 'clipboard-check' | 'clipboard-heart' | 'clipboard-list' | 'clipboard-remove' | 'clipboard-text' | 'document' | 'document-add' | 'document-medicine' | 'document-text' | 'documents' | 'documents-minimalistic' | 'download' | 'download-minimalistic' | 'download-square' | 'download-twice-square' | 'exit' | 'export' | 'forward' | 'forward-2' | 'import' | 'login' | 'login-2' | 'login-3' | 'logout' | 'logout-2' | 'logout-3' | 'maximize' | 'maximize-square' | 'maximize-square-2' | 'maximize-square-3' | 'maximize-square-minimalistic' | 'minimize' | 'minimize-square' | 'minimize-square-2' | 'minimize-square-3' | 'minimize-square-minimalistic' | 'notebook' | 'notes' | 'notes-minimalistic' | 'notification-lines-remove' | 'notification-remove' | 'notification-unread' | 'notification-unread-lines' | 'recive-square' | 'recive-twice-square' | 'reorder' | 'reply' | 'reply-2' | 'scale' | 'screen-share' | 'send-square' | 'send-twice-square' | 'square-bottom-down' | 'square-bottom-up' | 'square-top-down' | 'square-top-up' | 'undo-left' | 'undo-left-round' | 'undo-left-round-square' | 'undo-left-square' | 'undo-right' | 'undo-right-round' | 'undo-right-round-square' | 'undo-right-square' | 'upload' | 'upload-minimalistic' | 'upload-square' | 'upload-twice-square';
  'bold-duotone': 'archive' | 'archive-check' | 'archive-down' | 'archive-down-minimlistic' | 'archive-minimalistic' | 'archive-up' | 'archive-up-minimlistic' | 'arrow-to-down-left' | 'arrow-to-down-right' | 'arrow-to-top-left' | 'arrow-to-top-right' | 'bell' | 'bell-bing' | 'bell-off' | 'circle-bottom-down' | 'circle-bottom-up' | 'circle-top-down' | 'circle-top-up' | 'clipboard' | 'clipboard-add' | 'clipboard-check' | 'clipboard-heart' | 'clipboard-list' | 'clipboard-remove' | 'clipboard-text' | 'document' | 'document-add' | 'document-medicine' | 'document-text' | 'documents' | 'documents-minimalistic' | 'download' | 'download-minimalistic' | 'download-square' | 'download-twice-square' | 'exit' | 'export' | 'forward' | 'forward-2' | 'import' | 'login' | 'login-2' | 'login-3' | 'logout' | 'logout-2' | 'logout-3' | 'maximize' | 'maximize-square' | 'maximize-square-2' | 'maximize-square-3' | 'maximize-square-minimalistic' | 'minimize' | 'minimize-square' | 'minimize-square-2' | 'minimize-square-3' | 'minimize-square-minimalistic' | 'notebook' | 'notes' | 'notes-minimalistic' | 'notification-lines-remove' | 'notification-remove' | 'notification-unread' | 'notification-unread-lines' | 'recive-square' | 'recive-twice-square' | 'reorder' | 'reply' | 'reply-2' | 'scale' | 'screen-share' | 'send-square' | 'send-twice-square' | 'square-bottom-down' | 'square-bottom-up' | 'square-top-down' | 'square-top-up' | 'undo-left' | 'undo-left-round' | 'undo-left-round-square' | 'undo-left-square' | 'undo-right' | 'undo-right-round' | 'undo-right-round-square' | 'undo-right-square' | 'upload' | 'upload-minimalistic' | 'upload-square' | 'upload-twice-square';
  'broken': 'archive' | 'archive-check' | 'archive-down' | 'archive-down-minimlistic' | 'archive-minimalistic' | 'archive-up' | 'archive-up-minimlistic' | 'arrow-to-down-left' | 'arrow-to-down-right' | 'arrow-to-top-left' | 'arrow-to-top-right' | 'bell' | 'bell-bing' | 'bell-off' | 'circle-bottom-down' | 'circle-bottom-up' | 'circle-top-down' | 'circle-top-up' | 'clipboard' | 'clipboard-add' | 'clipboard-check' | 'clipboard-heart' | 'clipboard-list' | 'clipboard-remove' | 'clipboard-text' | 'document' | 'document-add' | 'document-medicine' | 'document-text' | 'documents' | 'documents-minimalistic' | 'download' | 'download-minimalistic' | 'download-square' | 'download-twice-square' | 'exit' | 'export' | 'forward' | 'forward-2' | 'import' | 'login' | 'login-2' | 'login-3' | 'logout' | 'logout-2' | 'logout-3' | 'maximize' | 'maximize-square' | 'maximize-square-2' | 'maximize-square-3' | 'maximize-square-minimalistic' | 'minimize' | 'minimize-square' | 'minimize-square-2' | 'minimize-square-3' | 'minimize-square-minimalistic' | 'notebook' | 'notes' | 'notes-minimalistic' | 'notification-lines-remove' | 'notification-remove' | 'notification-unread' | 'notification-unread-lines' | 'recive-square' | 'recive-twice-square' | 'reorder' | 'reply' | 'reply-2' | 'scale' | 'screen-share' | 'send-square' | 'send-twice-square' | 'square-bottom-down' | 'square-bottom-up' | 'square-top-down' | 'square-top-up' | 'undo-left' | 'undo-left-round' | 'undo-left-round-square' | 'undo-left-square' | 'undo-right' | 'undo-right-round' | 'undo-right-round-square' | 'undo-right-square' | 'upload' | 'upload-minimalistic' | 'upload-square' | 'upload-twice-square';
  'outline': 'archive' | 'archive-check' | 'archive-down' | 'archive-down-minimlistic' | 'archive-minimalistic' | 'archive-up' | 'archive-up-minimlistic' | 'arrow-to-down-left' | 'arrow-to-down-right' | 'arrow-to-top-left' | 'arrow-to-top-right' | 'bell' | 'bell-bing' | 'bell-off' | 'circle-bottom-down' | 'circle-bottom-up' | 'circle-top-down' | 'circle-top-up' | 'clipboard' | 'clipboard-check' | 'clipboard-heart' | 'clipboard-list' | 'clipboard-remove' | 'clipboard-text' | 'document' | 'document-add' | 'document-medicine' | 'document-text' | 'documents' | 'documents-minimalistic' | 'download' | 'download-minimalistic' | 'download-square' | 'download-twice-square' | 'exit' | 'export' | 'forward' | 'forward-2' | 'import' | 'login' | 'login-2' | 'login-3' | 'logout' | 'logout-2' | 'logout-3' | 'maximize' | 'maximize-square' | 'maximize-square-2' | 'maximize-square-3' | 'maximize-square-minimalistic' | 'minimize' | 'minimize-square' | 'minimize-square-2' | 'minimize-square-3' | 'minimize-square-minimalistic' | 'notebook' | 'notes' | 'notes-minimalistic' | 'notification-lines-remove' | 'notification-remove' | 'notification-unread' | 'notification-unread-lines' | 'recive-square' | 'recive-twice-square' | 'reorder' | 'reply' | 'reply-2' | 'scale' | 'screen-share' | 'send-square' | 'send-twice-square' | 'square-bottom-down' | 'square-bottom-up' | 'square-top-down' | 'square-top-up' | 'undo-left' | 'undo-left-round' | 'undo-left-round-square' | 'undo-left-square' | 'undo-right' | 'undo-right-round' | 'undo-right-round-square' | 'undo-right-square' | 'upload' | 'upload-minimalistic' | 'upload-square' | 'upload-twice-square';
  'outline-duotone': 'archive' | 'archive-check' | 'archive-down' | 'archive-down-minimlistic' | 'archive-minimalistic' | 'archive-up' | 'archive-up-minimlistic' | 'arrow-to-down-left' | 'arrow-to-down-right' | 'arrow-to-top-left' | 'arrow-to-top-right' | 'bell' | 'bell-bing' | 'bell-off' | 'circle-bottom-down' | 'circle-bottom-up' | 'circle-top-down' | 'circle-top-up' | 'clipboard' | 'clipboard-add' | 'clipboard-check' | 'clipboard-heart' | 'clipboard-list' | 'clipboard-remove' | 'clipboard-text' | 'document' | 'document-add' | 'document-medicine' | 'document-text' | 'documents' | 'documents-minimalistic' | 'download' | 'download-minimalistic' | 'download-square' | 'download-twice-square' | 'exit' | 'export' | 'forward' | 'forward-2' | 'import' | 'login' | 'login-2' | 'login-3' | 'logout' | 'logout-2' | 'logout-3' | 'maximize' | 'maximize-square' | 'maximize-square-2' | 'maximize-square-3' | 'maximize-square-minimalistic' | 'minimize' | 'minimize-square' | 'minimize-square-2' | 'minimize-square-3' | 'minimize-square-minimalistic' | 'notebook' | 'notes' | 'notes-minimalistic' | 'notification-lines-remove' | 'notification-remove' | 'notification-unread' | 'notification-unread-lines' | 'recive-square' | 'recive-twice-square' | 'reorder' | 'reply' | 'reply-2' | 'scale' | 'screen-share' | 'send-square' | 'send-twice-square' | 'square-bottom-down' | 'square-bottom-up' | 'square-top-down' | 'square-top-up' | 'undo-left' | 'undo-left-round' | 'undo-left-round-square' | 'undo-left-square' | 'undo-right' | 'undo-right-round' | 'undo-right-round-square' | 'upload' | 'upload-minimalistic' | 'upload-square' | 'upload-twice-square';
}

export type IconVariant = keyof IconNamesByVariant;
export type AnyIconName = IconNamesByVariant[IconVariant];
export type IconComponentProps = { size?: number; color?: string };
