export { Icon } from './Icon';
export { iconRegistry } from './registry';
export type { IconType } from './registry';
export type { IconProps } from './Icon';

// Export all individual icon components
// This file is generated by scripts/generate-icons.ts
export * from './components-exports';
