'use strict';
/**
 * Package entry for JS/React Native.
 * Exposes named exports for the component and the icon registry.
 */
const componentsExports = require('./components-exports');
const { Icon } = require('./Icon');
const { iconRegistry } = require('./registry');

// Export all individual icon components
// This file is generated by scripts/generate-icons.ts

module.exports = { Icon, iconRegistry, ...componentsExports };
